// Country data with phone regex patterns and formats
export interface Country {
    name: string;
    code: string;
    dialCode: string;
    flag: string;
    phoneRegex: RegExp;
    format: string;
}

export const countries: Country[] = [
    { name: 'Afghanistan', code: 'AF', dialCode: '+93', flag: '🇦🇫', phoneRegex: /^[2-7]\d{8}$/, format: 'XX XXX XXXX' },
    { name: 'Albania', code: 'AL', dialCode: '+355', flag: '🇦🇱', phoneRegex: /^[4-9]\d{7,8}$/, format: 'XX XXX XXXX' },
    { name: 'Algeria', code: 'DZ', dialCode: '+213', flag: '🇩🇿', phoneRegex: /^[5-7]\d{8}$/, format: 'XX XXX XXXX' },
    { name: 'Argentina', code: 'AR', dialCode: '+54', flag: '🇦🇷', phoneRegex: /^[1-9]\d{9,10}$/, format: 'XX XXXX XXXX' },
    { name: 'Armenia', code: 'AM', dialCode: '+374', flag: '🇦🇲', phoneRegex: /^[4-9]\d{7}$/, format: 'XX XXX XXX' },
    { name: 'Australia', code: 'AU', dialCode: '+61', flag: '🇦🇺', phoneRegex: /^4\d{8}$/, format: '4XX XXX XXX' },
    { name: 'Austria', code: 'AT', dialCode: '+43', flag: '🇦🇹', phoneRegex: /^[1-9]\d{7,10}$/, format: 'XXX XXX XXXX' },
    { name: 'Azerbaijan', code: 'AZ', dialCode: '+994', flag: '🇦🇿', phoneRegex: /^[4-9]\d{8}$/, format: 'XX XXX XXXX' },
    { name: 'Bahrain', code: 'BH', dialCode: '+973', flag: '🇧🇭', phoneRegex: /^[3-9]\d{7}$/, format: 'XXXX XXXX' },
    { name: 'Bangladesh', code: 'BD', dialCode: '+880', flag: '🇧🇩', phoneRegex: /^1[3-9]\d{8}$/, format: '1XXX XXXXXX' },
    { name: 'Belarus', code: 'BY', dialCode: '+375', flag: '🇧🇾', phoneRegex: /^[2-9]\d{8}$/, format: 'XX XXX XXXX' },
    { name: 'Belgium', code: 'BE', dialCode: '+32', flag: '🇧🇪', phoneRegex: /^[4-9]\d{7,8}$/, format: 'XXX XXX XXX' },
    { name: 'Brazil', code: 'BR', dialCode: '+55', flag: '🇧🇷', phoneRegex: /^[1-9]\d{10}$/, format: 'XX XXXXX XXXX' },
    { name: 'Bulgaria', code: 'BG', dialCode: '+359', flag: '🇧🇬', phoneRegex: /^[2-9]\d{7,8}$/, format: 'XX XXX XXXX' },
    { name: 'Cambodia', code: 'KH', dialCode: '+855', flag: '🇰🇭', phoneRegex: /^[1-9]\d{7,8}$/, format: 'XX XXX XXX' },
    { name: 'Canada', code: 'CA', dialCode: '+1', flag: '🇨🇦', phoneRegex: /^[2-9]\d{2}[2-9]\d{2}\d{4}$/, format: '(XXX) XXX-XXXX' },
    { name: 'Chile', code: 'CL', dialCode: '+56', flag: '🇨🇱', phoneRegex: /^[2-9]\d{8}$/, format: 'X XXXX XXXX' },
    { name: 'China', code: 'CN', dialCode: '+86', flag: '🇨🇳', phoneRegex: /^1[3-9]\d{9}$/, format: '1XX XXXX XXXX' },
    { name: 'Colombia', code: 'CO', dialCode: '+57', flag: '🇨🇴', phoneRegex: /^[3]\d{9}$/, format: 'XXX XXX XXXX' },
    { name: 'Croatia', code: 'HR', dialCode: '+385', flag: '🇭🇷', phoneRegex: /^[1-9]\d{7,8}$/, format: 'XX XXX XXXX' },
    { name: 'Cyprus', code: 'CY', dialCode: '+357', flag: '🇨🇾', phoneRegex: /^[2-9]\d{7}$/, format: 'XX XXX XXX' },
    { name: 'Czech Republic', code: 'CZ', dialCode: '+420', flag: '🇨🇿', phoneRegex: /^[2-9]\d{8}$/, format: 'XXX XXX XXX' },
    { name: 'Denmark', code: 'DK', dialCode: '+45', flag: '🇩🇰', phoneRegex: /^[2-9]\d{7}$/, format: 'XX XX XX XX' },
    { name: 'Egypt', code: 'EG', dialCode: '+20', flag: '🇪🇬', phoneRegex: /^1[0-9]\d{8}$/, format: '1X XXXX XXXX' },
    { name: 'Estonia', code: 'EE', dialCode: '+372', flag: '🇪🇪', phoneRegex: /^[5-9]\d{7}$/, format: 'XXXX XXXX' },
    { name: 'Finland', code: 'FI', dialCode: '+358', flag: '🇫🇮', phoneRegex: /^[4-9]\d{7,8}$/, format: 'XX XXX XXXX' },
    { name: 'France', code: 'FR', dialCode: '+33', flag: '🇫🇷', phoneRegex: /^[67]\d{8}$/, format: 'XX XX XX XX XX' },
    { name: 'Georgia', code: 'GE', dialCode: '+995', flag: '🇬🇪', phoneRegex: /^[5-9]\d{8}$/, format: 'XXX XXX XXX' },
    { name: 'Germany', code: 'DE', dialCode: '+49', flag: '🇩🇪', phoneRegex: /^1[5-7]\d{8,9}$/, format: '1XX XXXX XXXX' },
    { name: 'Ghana', code: 'GH', dialCode: '+233', flag: '🇬🇭', phoneRegex: /^[2-9]\d{8}$/, format: 'XX XXX XXXX' },
    { name: 'Greece', code: 'GR', dialCode: '+30', flag: '🇬🇷', phoneRegex: /^[6-9]\d{8}$/, format: 'XXX XXX XXXX' },
    { name: 'Hungary', code: 'HU', dialCode: '+36', flag: '🇭🇺', phoneRegex: /^[2-9]\d{7,8}$/, format: 'XX XXX XXXX' },
    { name: 'Iceland', code: 'IS', dialCode: '+354', flag: '🇮🇸', phoneRegex: /^[3-9]\d{7}$/, format: 'XXX XXXX' },
    { name: 'India', code: 'IN', dialCode: '+91', flag: '🇮🇳', phoneRegex: /^[6-9]\d{9}$/, format: 'XXXXX XXXXX' },
    { name: 'Indonesia', code: 'ID', dialCode: '+62', flag: '🇮🇩', phoneRegex: /^[8]\d{9,10}$/, format: 'XXX XXXX XXXX' },
    { name: 'Iran', code: 'IR', dialCode: '+98', flag: '🇮🇷', phoneRegex: /^9\d{9}$/, format: 'XXX XXX XXXX' },
    { name: 'Iraq', code: 'IQ', dialCode: '+964', flag: '🇮🇶', phoneRegex: /^7[3-9]\d{8}$/, format: 'XXX XXX XXXX' },
    { name: 'Ireland', code: 'IE', dialCode: '+353', flag: '🇮🇪', phoneRegex: /^[1-9]\d{8}$/, format: 'XX XXX XXXX' },
    { name: 'Israel', code: 'IL', dialCode: '+972', flag: '🇮🇱', phoneRegex: /^[2-9]\d{7,8}$/, format: 'XX XXX XXXX' },
    { name: 'Italy', code: 'IT', dialCode: '+39', flag: '🇮🇹', phoneRegex: /^3\d{8,9}$/, format: 'XXX XXX XXXX' },
    { name: 'Japan', code: 'JP', dialCode: '+81', flag: '🇯🇵', phoneRegex: /^[789]0\d{8}$/, format: 'XX XXXX XXXX' },
    { name: 'Jordan', code: 'JO', dialCode: '+962', flag: '🇯🇴', phoneRegex: /^7[7-9]\d{7}$/, format: 'XXX XXX XXX' },
    { name: 'Kazakhstan', code: 'KZ', dialCode: '+7', flag: '🇰🇿', phoneRegex: /^[7]\d{9}$/, format: 'X XXX XXX XXXX' },
    { name: 'Kenya', code: 'KE', dialCode: '+254', flag: '🇰🇪', phoneRegex: /^[17]\d{8}$/, format: 'XXX XXX XXX' },
    { name: 'Kuwait', code: 'KW', dialCode: '+965', flag: '🇰🇼', phoneRegex: /^[569]\d{7}$/, format: 'XXXX XXXX' },
    { name: 'Latvia', code: 'LV', dialCode: '+371', flag: '🇱🇻', phoneRegex: /^[2-9]\d{7}$/, format: 'XXXX XXXX' },
    { name: 'Lebanon', code: 'LB', dialCode: '+961', flag: '🇱🇧', phoneRegex: /^[3-9]\d{7}$/, format: 'XX XXX XXX' },
    { name: 'Lithuania', code: 'LT', dialCode: '+370', flag: '🇱🇹', phoneRegex: /^[6]\d{7}$/, format: 'XXX XXXXX' },
    { name: 'Luxembourg', code: 'LU', dialCode: '+352', flag: '🇱🇺', phoneRegex: /^[2-9]\d{7}$/, format: 'XXX XXX XXX' },
    { name: 'Malaysia', code: 'MY', dialCode: '+60', flag: '🇲🇾', phoneRegex: /^1[0-9]\d{7,8}$/, format: 'XX XXXX XXXX' },
    { name: 'Mexico', code: 'MX', dialCode: '+52', flag: '🇲🇽', phoneRegex: /^[1-9]\d{9,10}$/, format: 'XX XXXX XXXX' },
    { name: 'Morocco', code: 'MA', dialCode: '+212', flag: '🇲🇦', phoneRegex: /^[5-7]\d{8}$/, format: 'XX XXX XXXX' },
    { name: 'Netherlands', code: 'NL', dialCode: '+31', flag: '🇳🇱', phoneRegex: /^6\d{8}$/, format: 'XX XXX XXXX' },
    { name: 'New Zealand', code: 'NZ', dialCode: '+64', flag: '🇳🇿', phoneRegex: /^[2-9]\d{7,8}$/, format: 'XX XXX XXXX' },
    { name: 'Nigeria', code: 'NG', dialCode: '+234', flag: '🇳🇬', phoneRegex: /^[789]\d{9}$/, format: 'XXX XXX XXXX' },
    { name: 'Norway', code: 'NO', dialCode: '+47', flag: '🇳🇴', phoneRegex: /^[4-9]\d{7}$/, format: 'XXX XX XXX' },
    { name: 'Pakistan', code: 'PK', dialCode: '+92', flag: '🇵🇰', phoneRegex: /^3[0-9]\d{8}$/, format: 'XXX XXX XXXX' },
    { name: 'Philippines', code: 'PH', dialCode: '+63', flag: '🇵🇭', phoneRegex: /^9\d{9}$/, format: 'XXX XXX XXXX' },
    { name: 'Poland', code: 'PL', dialCode: '+48', flag: '🇵🇱', phoneRegex: /^[5-9]\d{8}$/, format: 'XXX XXX XXX' },
    { name: 'Portugal', code: 'PT', dialCode: '+351', flag: '🇵🇹', phoneRegex: /^9[1-9]\d{7}$/, format: 'XXX XXX XXX' },
    { name: 'Qatar', code: 'QA', dialCode: '+974', flag: '🇶🇦', phoneRegex: /^[3-7]\d{7}$/, format: 'XXXX XXXX' },
    { name: 'Romania', code: 'RO', dialCode: '+40', flag: '🇷🇴', phoneRegex: /^7[0-9]\d{7}$/, format: 'XXX XXX XXX' },
    { name: 'Russia', code: 'RU', dialCode: '+7', flag: '🇷🇺', phoneRegex: /^[9]\d{9}$/, format: 'XXX XXX XXXX' },
    { name: 'Saudi Arabia', code: 'SA', dialCode: '+966', flag: '🇸🇦', phoneRegex: /^5[0-9]\d{7}$/, format: 'XXX XXX XXX' },
    { name: 'Singapore', code: 'SG', dialCode: '+65', flag: '🇸🇬', phoneRegex: /^[89]\d{7}$/, format: 'XXXX XXXX' },
    { name: 'Slovakia', code: 'SK', dialCode: '+421', flag: '🇸🇰', phoneRegex: /^[2-9]\d{8}$/, format: 'XXX XXX XXX' },
    { name: 'Slovenia', code: 'SI', dialCode: '+386', flag: '🇸🇮', phoneRegex: /^[3-9]\d{7}$/, format: 'XX XXX XXX' },
    { name: 'South Africa', code: 'ZA', dialCode: '+27', flag: '🇿🇦', phoneRegex: /^[6-8]\d{8}$/, format: 'XX XXX XXXX' },
    { name: 'South Korea', code: 'KR', dialCode: '+82', flag: '🇰🇷', phoneRegex: /^1[0-9]\d{7,8}$/, format: 'XX XXXX XXXX' },
    { name: 'Spain', code: 'ES', dialCode: '+34', flag: '🇪🇸', phoneRegex: /^[6-9]\d{8}$/, format: 'XXX XXX XXX' },
    { name: 'Sri Lanka', code: 'LK', dialCode: '+94', flag: '🇱🇰', phoneRegex: /^7[0-9]\d{7}$/, format: 'XXX XXX XXX' },
    { name: 'Sweden', code: 'SE', dialCode: '+46', flag: '🇸🇪', phoneRegex: /^7[0-9]\d{7}$/, format: 'XXX XXX XXX' },
    { name: 'Switzerland', code: 'CH', dialCode: '+41', flag: '🇨🇭', phoneRegex: /^[2-9]\d{8}$/, format: 'XX XXX XX XX' },
    { name: 'Thailand', code: 'TH', dialCode: '+66', flag: '🇹🇭', phoneRegex: /^[689]\d{8}$/, format: 'XX XXX XXXX' },
    { name: 'Turkey', code: 'TR', dialCode: '+90', flag: '🇹🇷', phoneRegex: /^5[0-9]\d{8}$/, format: 'XXX XXX XXXX' },
    { name: 'Ukraine', code: 'UA', dialCode: '+380', flag: '🇺🇦', phoneRegex: /^[3-9]\d{8}$/, format: 'XX XXX XXXX' },
    { name: 'United Arab Emirates', code: 'AE', dialCode: '+971', flag: '🇦🇪', phoneRegex: /^5[0-9]\d{7}$/, format: 'XX XXX XXXX' },
    { name: 'United Kingdom', code: 'GB', dialCode: '+44', flag: '🇬🇧', phoneRegex: /^7\d{9}$/, format: '7XXX XXXXXX' },
    { name: 'United States', code: 'US', dialCode: '+1', flag: '🇺🇸', phoneRegex: /^[2-9]\d{2}[2-9]\d{2}\d{4}$/, format: '(XXX) XXX-XXXX' },
    { name: 'Vietnam', code: 'VN', dialCode: '+84', flag: '🇻🇳', phoneRegex: /^[3-9]\d{8}$/, format: 'XXX XXX XXXX' }
];