export const llcTypes = [
    { label: 'Single Member LLC', value: 'singleLLC' },
    { label: 'Multi Member LLC', value: 'multiLLC' },
];

export const companyTypes = [
    { label: 'Limited Liability Company', value: 'llc', },
    { label: 'Corporation', value: 'corp', },
    { label: 'Incorporated', value: 'inc', },
    { label: 'Limited', value: 'ltd', },
    { label: 'Partnership', value: 'partnership', },
    { label: 'Limited Partnership', value: 'lp', },
    { label: 'Professional Corporation', value: 'pc', },
    { label: 'Limited Liability Partnership', value: 'llp', },
    { label: 'Public Limited Company', value: 'plc', },
    { label: 'Private Limited Company', value: 'pvt',}
];

export const prioroty = [
    { label: 'High', value: 'high', },
    { label: 'Medium', value: 'medium', },
    { label: 'Low', value: 'low', }
];

export const serviceTypes = [
    { label: 'Consulting', value: 'consulting' },
    { label: 'Software Development', value: 'software_development' },
    { label: 'Digital Marketing', value: 'digital_marketing' },
    { label: 'Graphic Design', value: 'graphic_design' },
    { label: 'IT Services', value: 'it_services' },
    { label: 'Financial Services', value: 'financial_services' },
    { label: 'Healthcare Services', value: 'healthcare_services' },
    { label: 'Education & Training', value: 'education_training' },
    { label: 'Legal Services', value: 'legal_services' },
    { label: 'Construction Services', value: 'construction_services' },
    { label: 'Logistics & Transportation', value: 'logistics_transportation' },
    { label: 'Hospitality & Tourism', value: 'hospitality_tourism' },
    { label: 'Real Estate Services', value: 'real_estate' },
    { label: 'Event Management', value: 'event_management' },
    { label: 'Cleaning Services', value: 'cleaning_services' },
];

export const s_corpTypes = [
    { label: 'S Corporation (Owners must be U.S Resident)', value: 's_corp' },
]

export const YesNo = [
    { label: 'Yes', value: 'yes' },
    { label: 'No', value: 'no' }
]

export const c_corpTypes = [
    { label: 'C Corporation', value: 'c_corp' },
]

export const partnarshipTypes = [
    { label: 'Partnership', value: 'partnership' },]

export const manageTypes = [
    { label: 'Member Manage', value: 'member_manage' },
    { label: 'Manager Mange', value: 'manager_manage' },
    ]

export const industries = [
    { label: 'Technology', value: 'technology' },
    { label: 'Healthcare', value: 'healthcare' },
    { label: 'Finance', value: 'finance' },
    { label: 'Real Estate', value: 'real_estate' },
    { label: 'E-commerce', value: 'ecommerce' },
    { label: 'Education', value: 'education' },
    { label: 'Hospitality', value: 'hospitality' },
    { label: 'Manufacturing', value: 'manufacturing' },
    { label: 'Transportation & Logistics', value: 'transportation' },
    { label: 'Media & Entertainment', value: 'media' },
];

export const countries = [
    { label: 'Afghanistan', value: 'af' },
    { label: 'Albania', value: 'al' },
    { label: 'Algeria', value: 'dz' },
    { label: 'Andorra', value: 'ad' },
    { label: 'Angola', value: 'ao' },
    { label: 'Antigua and Barbuda', value: 'ag' },
    { label: 'Argentina', value: 'ar' },
    { label: 'Armenia', value: 'am' },
    { label: 'Australia', value: 'au' },
    { label: 'Austria', value: 'at' },
    { label: 'Azerbaijan', value: 'az' },
    { label: 'Bahamas', value: 'bs' },
    { label: 'Bahrain', value: 'bh' },
    { label: 'Bangladesh', value: 'bd' },
    { label: 'Barbados', value: 'bb' },
    { label: 'Belarus', value: 'by' },
    { label: 'Belgium', value: 'be' },
    { label: 'Belize', value: 'bz' },
    { label: 'Benin', value: 'bj' },
    { label: 'Bhutan', value: 'bt' },
    { label: 'Bolivia', value: 'bo' },
    { label: 'Bosnia and Herzegovina', value: 'ba' },
    { label: 'Botswana', value: 'bw' },
    { label: 'Brazil', value: 'br' },
    { label: 'Brunei', value: 'bn' },
    { label: 'Bulgaria', value: 'bg' },
    { label: 'Burkina Faso', value: 'bf' },
    { label: 'Burundi', value: 'bi' },
    { label: 'Cambodia', value: 'kh' },
    { label: 'Cameroon', value: 'cm' },
    { label: 'Canada', value: 'ca' },
    { label: 'Cape Verde', value: 'cv' },
    { label: 'Central African Republic', value: 'cf' },
    { label: 'Chad', value: 'td' },
    { label: 'Chile', value: 'cl' },
    { label: 'China', value: 'cn' },
    { label: 'Colombia', value: 'co' },
    { label: 'Comoros', value: 'km' },
    { label: 'Congo', value: 'cg' },
    { label: 'Costa Rica', value: 'cr' },
    { label: 'Croatia', value: 'hr' },
    { label: 'Cuba', value: 'cu' },
    { label: 'Cyprus', value: 'cy' },
    { label: 'Czech Republic', value: 'cz' },
    { label: 'Denmark', value: 'dk' },
    { label: 'Djibouti', value: 'dj' },
    { label: 'Dominica', value: 'dm' },
    { label: 'Dominican Republic', value: 'do' },
    { label: 'Ecuador', value: 'ec' },
    { label: 'Egypt', value: 'eg' },
    { label: 'El Salvador', value: 'sv' },
    { label: 'Equatorial Guinea', value: 'gq' },
    { label: 'Eritrea', value: 'er' },
    { label: 'Estonia', value: 'ee' },
    { label: 'Eswatini', value: 'sz' },
    { label: 'Ethiopia', value: 'et' },
    { label: 'Fiji', value: 'fj' },
    { label: 'Finland', value: 'fi' },
    { label: 'France', value: 'fr' },
    { label: 'Gabon', value: 'ga' },
    { label: 'Gambia', value: 'gm' },
    { label: 'Georgia', value: 'ge' },
    { label: 'Germany', value: 'de' },
    { label: 'Ghana', value: 'gh' },
    { label: 'Greece', value: 'gr' },
    { label: 'Grenada', value: 'gd' },
    { label: 'Guatemala', value: 'gt' },
    { label: 'Guinea', value: 'gn' },
    { label: 'Guinea-Bissau', value: 'gw' },
    { label: 'Guyana', value: 'gy' },
    { label: 'Haiti', value: 'ht' },
    { label: 'Honduras', value: 'hn' },
    { label: 'Hungary', value: 'hu' },
    { label: 'Iceland', value: 'is' },
    { label: 'India', value: 'in' },
    { label: 'Indonesia', value: 'id' },
    { label: 'Iran', value: 'ir' },
    { label: 'Iraq', value: 'iq' },
    { label: 'Ireland', value: 'ie' },
    { label: 'Israel', value: 'il' },
    { label: 'Italy', value: 'it' },
    { label: 'Jamaica', value: 'jm' },
    { label: 'Japan', value: 'jp' },
    { label: 'Jordan', value: 'jo' },
    { label: 'Kazakhstan', value: 'kz' },
    { label: 'Kenya', value: 'ke' },
    { label: 'Kiribati', value: 'ki' },
    { label: 'Kuwait', value: 'kw' },
    { label: 'Kyrgyzstan', value: 'kg' },
    { label: 'Laos', value: 'la' },
    { label: 'Latvia', value: 'lv' },
    { label: 'Lebanon', value: 'lb' },
    { label: 'Lesotho', value: 'ls' },
    { label: 'Liberia', value: 'lr' },
    { label: 'Libya', value: 'ly' },
    { label: 'Liechtenstein', value: 'li' },
    { label: 'Lithuania', value: 'lt' },
    { label: 'Luxembourg', value: 'lu' },
    { label: 'Madagascar', value: 'mg' },
    { label: 'Malawi', value: 'mw' },
    { label: 'Malaysia', value: 'my' },
    { label: 'Maldives', value: 'mv' },
    { label: 'Mali', value: 'ml' },
    { label: 'Malta', value: 'mt' },
    { label: 'Marshall Islands', value: 'mh' },
    { label: 'Mauritania', value: 'mr' },
    { label: 'Mauritius', value: 'mu' },
    { label: 'Mexico', value: 'mx' },
    { label: 'Micronesia', value: 'fm' },
    { label: 'Moldova', value: 'md' },
    { label: 'Monaco', value: 'mc' },
    { label: 'Mongolia', value: 'mn' },
    { label: 'Montenegro', value: 'me' },
    { label: 'Morocco', value: 'ma' },
    { label: 'Mozambique', value: 'mz' },
    { label: 'Myanmar', value: 'mm' },
    { label: 'Namibia', value: 'na' },
    { label: 'Nauru', value: 'nr' },
    { label: 'Nepal', value: 'np' },
    { label: 'Netherlands', value: 'nl' },
    { label: 'New Zealand', value: 'nz' },
    { label: 'Nicaragua', value: 'ni' },
    { label: 'Niger', value: 'ne' },
    { label: 'Nigeria', value: 'ng' },
    { label: 'North Korea', value: 'kp' },
    { label: 'North Macedonia', value: 'mk' },
    { label: 'Norway', value: 'no' },
    { label: 'Oman', value: 'om' },
    { label: 'Pakistan', value: 'pk' },
    { label: 'Palau', value: 'pw' },
    { label: 'Palestine', value: 'ps' },
    { label: 'Panama', value: 'pa' },
    { label: 'Papua New Guinea', value: 'pg' },
    { label: 'Paraguay', value: 'py' },
    { label: 'Peru', value: 'pe' },
    { label: 'Philippines', value: 'ph' },
    { label: 'Poland', value: 'pl' },
    { label: 'Portugal', value: 'pt' },
    { label: 'Qatar', value: 'qa' },
    { label: 'Romania', value: 'ro' },
    { label: 'Russia', value: 'ru' },
    { label: 'Rwanda', value: 'rw' },
    { label: 'Saint Kitts and Nevis', value: 'kn' },
    { label: 'Saint Lucia', value: 'lc' },
    { label: 'Saint Vincent and the Grenadines', value: 'vc' },
    { label: 'Samoa', value: 'ws' },
    { label: 'San Marino', value: 'sm' },
    { label: 'Sao Tome and Principe', value: 'st' },
    { label: 'Saudi Arabia', value: 'sa' },
    { label: 'Senegal', value: 'sn' },
    { label: 'Serbia', value: 'rs' },
    { label: 'Seychelles', value: 'sc' },
    { label: 'Sierra Leone', value: 'sl' },
    { label: 'Singapore', value: 'sg' },
    { label: 'Slovakia', value: 'sk' },
    { label: 'Slovenia', value: 'si' },
    { label: 'Solomon Islands', value: 'sb' },
    { label: 'Somalia', value: 'so' },
    { label: 'South Africa', value: 'za' },
    { label: 'South Korea', value: 'kr' },
    { label: 'South Sudan', value: 'ss' },
    { label: 'Spain', value: 'es' },
    { label: 'Sri Lanka', value: 'lk' },
    { label: 'Sudan', value: 'sd' },
    { label: 'Suriname', value: 'sr' },
    { label: 'Sweden', value: 'se' },
    { label: 'Switzerland', value: 'ch' },
    { label: 'Syria', value: 'sy' },
    { label: 'Taiwan', value: 'tw' },
    { label: 'Tajikistan', value: 'tj' },
    { label: 'Tanzania', value: 'tz' },
    { label: 'Thailand', value: 'th' },
    { label: 'Timor-Leste', value: 'tl' },
    { label: 'Togo', value: 'tg' },
    { label: 'Tonga', value: 'to' },
    { label: 'Trinidad and Tobago', value: 'tt' },
    { label: 'Tunisia', value: 'tn' },
    { label: 'Turkey', value: 'tr' },
    { label: 'Turkmenistan', value: 'tm' },
    { label: 'Tuvalu', value: 'tv' },
    { label: 'Uganda', value: 'ug' },
    { label: 'Ukraine', value: 'ua' },
    { label: 'United Arab Emirates', value: 'ae' },
    { label: 'United Kingdom', value: 'gb' },
    { label: 'United States', value: 'us' },
    { label: 'Uruguay', value: 'uy' },
    { label: 'Uzbekistan', value: 'uz' },
    { label: 'Vanuatu', value: 'vu' },
    { label: 'Vatican City', value: 'va' },
    { label: 'Venezuela', value: 've' },
    { label: 'Vietnam', value: 'vn' },
    { label: 'Yemen', value: 'ye' },
    { label: 'Zambia', value: 'zm' },
    { label: 'Zimbabwe', value: 'zw' },
];

export const usStates = [
    { label: 'Alabama', value: 'Alabama' },
    { label: 'Alaska', value: 'Alaska' },
    { label: 'Arizona', value: 'Arizona' },
    { label: 'Arkansas', value: 'Arkansas' },
    { label: 'California', value: 'California' },
    { label: 'Colorado', value: 'Colorado' },
    { label: 'Connecticut', value: 'Connecticut' },
    { label: 'Delaware', value: 'Delaware' },
    { label: 'Florida', value: 'Florida' },
    { label: 'Georgia', value: 'Georgia' },
    { label: 'Hawaii', value: 'Hawaii' },
    { label: 'Idaho', value: 'Idaho' },
    { label: 'Illinois', value: 'Illinois' },
    { label: 'Indiana', value: 'Indiana' },
    { label: 'Iowa', value: 'Iowa' },
    { label: 'Kansas', value: 'Kansas' },
    { label: 'Kentucky', value: 'Kentucky' },
    { label: 'Louisiana', value: 'Louisiana' },
    { label: 'Maine', value: 'Maine' },
    { label: 'Maryland', value: 'Maryland' },
    { label: 'Massachusetts', value: 'Massachusetts' },
    { label: 'Michigan', value: 'Michigan' },
    { label: 'Minnesota', value: 'Minnesota' },
    { label: 'Mississippi', value: 'Mississippi' },
    { label: 'Missouri', value: 'Missouri' },
    { label: 'Montana', value: 'Montana' },
    { label: 'Nebraska', value: 'Nebraska' },
    { label: 'Nevada', value: 'Nevada' },
    { label: 'New Hampshire', value: 'New Hampshire' },
    { label: 'New Jersey', value: 'New Jersey' },
    { label: 'New Mexico', value: 'New Mexico' },
    { label: 'New York', value: 'New York' },
    { label: 'North Carolina', value: 'North Carolina' },
    { label: 'North Dakota', value: 'North Dakota' },
    { label: 'Ohio', value: 'Ohio' },
    { label: 'Oklahoma', value: 'Oklahoma' },
    { label: 'Oregon', value: 'Oregon' },
    { label: 'Pennsylvania', value: 'Pennsylvania' },
    { label: 'Rhode Island', value: 'Rhode Island' },
    { label: 'South Carolina', value: 'South Carolina' },
    { label: 'South Dakota', value: 'South Dakota' },
    { label: 'Tennessee', value: 'Tennessee' },
    { label: 'Texas', value: 'Texas' },
    { label: 'Utah', value: 'Utah' },
    { label: 'Vermont', value: 'Vermont' },
    { label: 'Virginia', value: 'Virginia' },
    { label: 'Washington', value: 'Washington' },
    { label: 'West Virginia', value: 'West Virginia' },
    { label: 'Wisconsin', value: 'Wisconsin' },
    { label: 'Wyoming', value: 'Wyoming' },
];

export const numOfOwnerShip = [
    { label: '2', value: 2 },
    { label: '3', value: 3 },
    { label: '4', value: 4 },
    { label: '5', value: 5 },
]