import PageHeader from "@/componant/ui/PageHeader";

export const metadata = {
  title: "Terms of Service - Steady Formation",
  description:
    "The terms that govern your access to and use of the Steady Formation website, dashboard, and related services.",
};

const termsOfServiceHtml = `<p><strong>Last Updated: </strong>August 9, 2026</p>
<p>Welcome to Steady Formation (&quot;Steady Formation,&quot; &quot;Company,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). These Terms of Service (the &quot;Terms&quot;) govern your access to and use of <a href="https://steadyformation.com" target="_blank" rel="noopener noreferrer" class="text-[#7856FC] hover:underline">https://steadyformation.com</a>, our customer dashboard, order forms, communications, and any products, features, tools, documents, filings, and services we provide (collectively, the &quot;Services&quot;).</p>
<p>By accessing the Services, creating an account, submitting information, placing an order, clicking to accept, or purchasing a service, you acknowledge that you have read, understood, and agree to be bound by these Terms, our <a href="/privacy" class="text-[#7856FC] hover:underline">Privacy Policy</a>, our <a href="/refund-policy" class="text-[#7856FC] hover:underline">Refund Policy</a>, and any service-specific terms or checkout disclosures that apply to your order. If you do not agree, do not use the Services.</p>
<h2>1. Eligibility and Authority</h2>
<p>You must be at least 18 years old and legally capable of entering into a binding agreement to use the Services.</p>
<p>If you use the Services on behalf of a business, company, applicant, owner, manager, officer, or other entity, you represent and warrant that you have authority to act for that person or entity and to bind that person or entity to these Terms.</p>
<p>You may not use the Services if you are prohibited from doing so under applicable law, sanctions rules, export-control rules, court order, or government restriction.</p>
<h2>2. Our Services</h2>
<p>Steady Formation provides business formation and related business-support services. Depending on the package, order page, written quote, or service description, the Services may include:</p>
<ul><li>U.S. limited liability company (LLC) formation;</li><li>U.S. corporation formation, including C Corporation services and S Corporation election-related assistance where available and legally eligible;</li><li>company name availability assistance;</li><li>registered agent coordination or registered agent services;</li><li>Employer Identification Number (EIN) application assistance;</li><li>business address, virtual address, or mail-related services where offered;</li><li>operating agreement, bylaws, resolutions, and other business document templates;</li><li>state filing and expedited filing assistance;</li><li>compliance reminders and business-support guidance;</li><li>dashboard access, order tracking, and customer support;</li><li>affiliate, referral, or promotional programs; and</li><li>other services displayed on our website or offered by our team.</li></ul>
<p>The exact scope, price, inclusions, exclusions, delivery estimates, and required customer actions for a service are those shown on the applicable checkout page, order page, package description, invoice, proposal, dashboard notice, or written communication at the time of purchase.</p>
<h2>3. We Are Not a Government Agency, Law Firm, Bank, or Accounting Firm</h2>
<p>Steady Formation is a private business-service provider. We are not the Internal Revenue Service (IRS), a Secretary of State, FinCEN, a state tax agency, a bank, a payment processor, a registered agent agency, or any other federal, state, or local government agency.</p>
<p>Unless expressly stated in a separate written engagement signed by an authorized representative of Steady Formation, information, templates, recommendations, filing assistance, and support provided through the Services are for general informational and business-administration purposes only. They do not constitute legal, tax, accounting, investment, financial, immigration, or professional advice.</p>
<p>You are responsible for obtaining advice from appropriately licensed professionals when your facts, ownership structure, tax position, industry, location, residency, or compliance obligations require it.</p>
<h2>4. Customer Information, Documents, and Cooperation</h2>
<p>You agree to provide complete, accurate, current, lawful, and authorized information. This may include information about you, your business, its owners, members, managers, shareholders, directors, officers, responsible parties, beneficial owners, addresses, business activities, tax information, payment details, signatures, identification, and other information needed to perform the requested Services.</p>
<p>You are responsible for reviewing all information before a filing, application, order, or document is submitted. You must promptly notify us of any error, change, mismatch, outdated detail, or unauthorized information.</p>
<p>Where our website states that no documents are required for a particular offer, that statement applies only to the ordinary information needed to begin that specific order unless the offer clearly says otherwise. It does not prevent Steady Formation, a government agency, registered agent provider, address provider, payment processor, bank, identity-verification provider, tax authority, or other third party from requesting identification, signatures, proof of address, ownership details, tax forms, or other documents when required.</p>
<p>Failure to provide required information, approvals, signatures, documents, or follow-up responses may delay, suspend, or prevent completion of a Service and may affect refund eligibility under our <a href="/refund-policy" class="text-[#7856FC] hover:underline">Refund Policy</a>.</p>
<h2>5. Authorization to Prepare, Submit, and Communicate About Filings</h2>
<p>When you purchase a filing, application, document, registered agent, address, tax-related, or business-support service, you authorize Steady Formation and, where necessary, our employees, contractors, affiliates, vendors, filing partners, registered agent providers, address providers, payment processors, and other service providers to prepare, transmit, submit, receive, and communicate about documents, applications, information, and related records using the information you provide.</p>
<p>This authorization is limited to performing, administering, supporting, securing, or correcting the Services you requested, responding to related agency or provider inquiries, and maintaining required business records.</p>
<p>Where an electronic signature, consent, appointment, authorization, filing acknowledgment, postal form, tax form, or account action is required, you authorize its use only to the extent necessary to complete the requested service or comply with applicable requirements. You remain responsible for the truthfulness, accuracy, legality, and authorization of the information supplied.</p>
<h2>6. Government and Third-Party Decisions</h2>
<p>Government agencies and third-party providers control their own eligibility rules, processing times, fees, approvals, rejections, requests for information, technical systems, verification standards, and decisions.</p>
<p>Steady Formation cannot guarantee:</p>
<ul><li>approval of a company name, filing, EIN, tax election, registered agent appointment, bank account, payment account, address verification, marketplace account, license, permit, or other application;</li><li>processing, approval, or delivery by a specific date unless we expressly guarantee that date in writing;</li><li>acceptance by a bank, payment processor, marketplace, government agency, registered agent provider, address provider, or other third party;</li><li>that a service will produce a particular tax, legal, banking, payment, marketplace, financing, credit, immigration, or regulatory result; or</li><li>that laws, forms, fees, rules, agency practices, processing times, or third-party requirements will remain unchanged.</li></ul>
<p>We will use commercially reasonable efforts to perform the Services we control, but we are not responsible for delays, denials, requests, outages, rejections, or decisions caused by government agencies or third parties outside our reasonable control.</p>
<h2>7. Company Formation Services</h2>
<p>You are responsible for choosing the entity type, state of formation, ownership structure, management structure, tax classification, and business purpose that fit your circumstances. Any general guidance we provide is informational only.</p>
<p>Company formation is not complete until the relevant government authority accepts the filing. Processing times shown on our website are estimates unless a specific written guarantee says otherwise.</p>
<p>After formation, your company may have ongoing federal, state, local, tax, licensing, reporting, registered agent, address, franchise tax, annual report, beneficial ownership, recordkeeping, and other compliance obligations. Unless a specific obligation is expressly included in your purchased package, you remain responsible for identifying, monitoring, and satisfying that obligation.</p>
<p>We may refuse or delay a filing if the information supplied appears incomplete, inconsistent, unlawful, unauthorized, misleading, high-risk, or likely to cause rejection.</p>
<h2>8. EIN and Tax-Related Assistance</h2>
<p>When we assist with an EIN, tax election, tax form, or other tax-related filing, you authorize us to prepare and submit the application or assist with the process based on the information you provide and, where permitted, communicate regarding the application.</p>
<p>The IRS or another competent authority may request additional information, verification, corrected information, or additional processing time. Approval and timing are controlled by the relevant authority.</p>
<p>Steady Formation does not guarantee a particular tax treatment, tax result, EIN approval date, S Corporation election acceptance, filing position, refund, deduction, withholding result, or eligibility for any tax classification. You should consult a qualified tax professional for advice about your specific tax situation.</p>
<h2>9. Registered Agent, Business Address, and Mail-Related Services</h2>
<p>Registered agent, business address, virtual address, mail handling, scanning, forwarding, or similar services may be provided directly by Steady Formation or through third-party providers and may be subject to additional provider terms, postal requirements, verification rules, forms, identity checks, and usage restrictions.</p>
<p>You agree that any registered agent, business address, or mail-related service will be used only for lawful, accurate, and authorized business purposes. Unless expressly permitted in writing, you may not represent a registered agent address, virtual address, or business address as a residential address, physical storefront, personal residence, proof of occupancy, or location where you physically conduct business.</p>
<p>Mail handling, scanning, forwarding, storage, package acceptance, postage, shipping, courier service, return mail, prohibited mail items, identity verification, address-change requirements, and additional charges may apply depending on the selected service and provider.</p>
<p>We may suspend, restrict, or terminate address-related or mail-related services if they are used unlawfully, deceptively, in violation of provider requirements, in violation of postal rules, or in a way that creates legal, compliance, security, fraud, or operational risk.</p>
<h2>10. Business Documents and Templates</h2>
<p>Operating agreements, bylaws, resolutions, forms, checklists, guides, and other documents or templates are provided for general business use and convenience. They may not address your specific legal, tax, ownership, operational, regulatory, financing, employment, licensing, or contractual circumstances.</p>
<p>Templates are provided on an &quot;as is&quot; basis and are not a substitute for advice from a qualified attorney, accountant, tax professional, or other licensed adviser. You are responsible for reviewing, customizing, approving, signing, storing, and using documents appropriately.</p>
<h2>11. Accounts, Dashboard Access, and Security</h2>
<p>You may be required to create an account or use a dashboard to access certain Services. You agree to provide accurate account information, keep your login credentials confidential, and promptly notify us if you suspect unauthorized access, fraud, misuse, or a security issue.</p>
<p>You are responsible for activity conducted through your account unless applicable law provides otherwise. We may suspend, restrict, or require additional verification for account access to protect the account, investigate suspected fraud, enforce these Terms, comply with law, or protect our systems, customers, partners, or service providers.</p>
<p>We may send notices, requests, updates, and service communications through your dashboard, email, phone, SMS, messaging platform, or other contact method you provide.</p>
<h2>12. Fees, Payments, and Government Charges</h2>
<p>You agree to pay all amounts disclosed at the time of purchase or otherwise agreed in writing.</p>
<p>Prices may include Steady Formation service fees and may also include or exclude government filing fees, taxes, registered agent fees, business address fees, mail-handling fees, expedited processing fees, payment processing fees, postage, courier charges, software charges, third-party provider fees, or other costs. The applicable checkout page, invoice, written quote, or service-specific disclosure controls.</p>
<p>Government and third-party fees may change without notice. If a required fee changes before submission or activation, we may request the difference before completing the Service. If you do not pay the required amount, the Service may be delayed, suspended, or cancelled subject to our <a href="/refund-policy" class="text-[#7856FC] hover:underline">Refund Policy</a>.</p>
<p>You represent that you are authorized to use the payment method submitted. We may use third-party payment processors to process payments. We do not require you to provide payment-card data directly to us when a transaction is processed entirely by a third-party payment provider.</p>
<p>We may refuse, hold, cancel, or reverse a transaction where we reasonably suspect fraud, unauthorized payment activity, sanctions risk, illegality, pricing error, misuse of the Services, or violation of these Terms.</p>
<h2>13. $0 Formation Offers, Promotions, and Discounts</h2>
<p>From time to time, Steady Formation may advertise promotional, discounted, bundled, or &quot;$0 formation&quot; offers. Unless the specific offer clearly states otherwise, a &quot;$0&quot; offer refers only to the Steady Formation service fee for the identified formation service and does not waive mandatory state filing fees, taxes, registered agent fees, business address fees, payment processing fees, optional add-ons, expedited fees, shipping, postage, future renewal charges, or other third-party charges.</p>
<p>Promotional eligibility, availability, duration, package inclusions, exclusions, limits, renewal terms, and required customer actions may vary. The terms displayed with the promotion at the time of order will control if they conflict with these general Terms.</p>
<p>We may correct obvious pricing or typographical errors and may refuse or cancel an order that is placed through misuse, technical error, unauthorized coupon use, or ineligibility for the offer.</p>
<h2>14. Subscriptions, Renewals, and Recurring Services</h2>
<p>Some Services, including registered agent, business address, mail handling, compliance, dashboard, support, or similar recurring services, may renew periodically.</p>
<p>If a Service is sold as a recurring subscription, the billing frequency, renewal price, and material renewal terms will be disclosed before purchase or in the applicable order documentation. By purchasing a recurring Service, you authorize us or our payment provider to charge the applicable renewal amount, taxes, and related fees using your payment method until you cancel.</p>
<p>You may request cancellation of future renewal charges through your account, where available, or by contacting us at info@steadyformation.com. Cancellation must be received before the next renewal is processed. Cancellation does not automatically create a right to refund amounts already earned, incurred, paid to government agencies or third parties, or covering an active billing period.</p>
<p>If payment fails, we may retry the payment, request an updated payment method, suspend the recurring Service, apply late fees where disclosed and lawful, or terminate the Service after reasonable notice where appropriate.</p>
<h2>15. Refunds, Cancellations, and Abandoned Orders</h2>
<p>Refunds and cancellations are governed by our <a href="/refund-policy" class="text-[#7856FC] hover:underline">Refund Policy</a>.</p>
<p>Where our website describes a service as carrying a money-back guarantee, that guarantee is subject to the eligibility conditions, exclusions, timing rules, and non-refundable government or third-party charges described in the <a href="/refund-policy" class="text-[#7856FC] hover:underline">Refund Policy</a> unless a specific written offer provides more favorable terms.</p>
<p>You are responsible for responding to reasonable requests for information, approval, signatures, documents, corrections, or verification. If you do not respond within the timeframe stated in the <a href="/refund-policy" class="text-[#7856FC] hover:underline">Refund Policy</a> or applicable service communication, the order may be treated as delayed, inactive, abandoned, forfeited, or closed. Amounts already earned, incurred, submitted, paid to third parties, or committed to the Service may be non-refundable.</p>
<h2>16. Electronic Communications, Notices, and Consent</h2>
<p>By using the Services, you consent to receive electronic communications from us, including agreements, invoices, receipts, account notices, order updates, renewal notices, filing requests, support messages, marketing messages where permitted, and legal notices.</p>
<p>Electronic communications may be sent by email, dashboard notice, SMS, phone, messaging platform, website notice, or other contact method you provide. You agree that electronic records, notices, signatures, consents, and communications satisfy any legal requirement that such communications be in writing, to the extent permitted by law.</p>
<p>You are responsible for keeping your contact information current and for checking messages relating to your orders and Services.</p>
<h2>17. Marketing Communications</h2>
<p>Where permitted by law, we may send newsletters, service updates, offers, or promotional communications. You may opt out of marketing emails using the unsubscribe link or by contacting us.</p>
<p>Opting out of marketing communications does not prevent us from sending transactional or service-related messages concerning your account, orders, filings, renewals, security, legal notices, or support requests.</p>
<h2>18. Acceptable Use</h2>
<p>You may not use the Services to:</p>
<ul><li>violate any law, regulation, sanctions requirement, export-control rule, court order, or third-party right;</li><li>create, maintain, or support an entity, account, address, or filing for fraud, deception, money laundering, tax evasion, sanctions evasion, prohibited transactions, identity misuse, or other unlawful activity;</li><li>submit false, misleading, stolen, forged, unauthorized, incomplete, or deceptive information;</li><li>impersonate another person or entity or misrepresent your authority;</li><li>use an address, registered agent, document, filing, or account in a deceptive or unlawful manner;</li><li>interfere with, probe, scan, damage, reverse engineer, scrape, overload, or disrupt our website, dashboard, systems, security controls, or service providers;</li><li>upload malicious code or attempt unauthorized access;</li><li>harvest, copy, or commercially exploit our content, data, systems, or workflows without authorization; or</li><li>use our content, systems, documents, or Services in a way that infringes intellectual property, privacy, publicity, or other rights.</li></ul>
<p>We may refuse, suspend, or discontinue Services where reasonably necessary to comply with law, prevent fraud or abuse, protect third parties, protect service providers, enforce these Terms, or reduce legal, security, compliance, or reputational risk.</p>
<h2>19. Prohibited and High-Risk Activities</h2>
<p>We may decline or discontinue Services for businesses, activities, transactions, jurisdictions, individuals, or entities that we determine, in our reasonable discretion, are unlawful, prohibited by a provider, unusually high-risk, unsupported, or inconsistent with our compliance obligations.</p>
<p>This may include businesses involving fraud, deceptive practices, counterfeit goods, illegal drugs, unlicensed regulated activity, sanctions exposure, unlawful gambling, adult exploitation, hate or violence, weapons violations, unauthorized financial services, or any activity prohibited by a government agency, payment provider, registered agent provider, address provider, bank, marketplace, or other relevant third party.</p>
<p>We are not required to provide a detailed explanation where doing so could compromise security, fraud prevention, compliance, legal obligations, or provider requirements.</p>
<h2>20. Intellectual Property</h2>
<p>The Steady Formation website, dashboard, branding, graphics, logos, software, text, page designs, documents, original content, workflows, and related materials are owned by or licensed to Steady Formation and are protected by applicable intellectual property laws.</p>
<p>Except as permitted by law or expressly authorized in writing, you may not copy, reproduce, distribute, modify, republish, sell, scrape, train models on, or commercially exploit our proprietary content, documents, software, systems, or materials.</p>
<p>You retain ownership of information and materials you provide to us. You grant us a limited, worldwide, non-exclusive, royalty-free license to use, host, store, copy, transmit, process, display, and disclose those materials only as reasonably necessary to provide, administer, secure, improve, support, document, and enforce the Services and as otherwise described in our <a href="/privacy" class="text-[#7856FC] hover:underline">Privacy Policy</a>.</p>
<h2>21. Feedback, Reviews, and Testimonials</h2>
<p>If you voluntarily provide suggestions, ideas, reviews, testimonials, ratings, or feedback about the Services, you grant Steady Formation a worldwide, perpetual, irrevocable, royalty-free, transferable, and sublicensable right to use that feedback for lawful business purposes without compensation to you, subject to our <a href="/privacy" class="text-[#7856FC] hover:underline">Privacy Policy</a> and applicable law.</p>
<p>You represent that any review or testimonial you provide is truthful, reflects your genuine experience, and does not violate the rights of another person or entity.</p>
<h2>22. Copyright and Intellectual Property Complaints</h2>
<p>If you believe content on our Services infringes your copyright or other intellectual property rights, contact us at <a href="mailto:info@steadyformation.com" class="text-[#7856FC] hover:underline">info@steadyformation.com</a> and provide:</p>
<ul><li>your name, company name if applicable, mailing address, email address, and phone number;</li><li>identification of the copyrighted work or other protected material;</li><li>identification and location of the allegedly infringing material;</li><li>a statement explaining your good-faith belief that the use is not authorized by the rights owner, its agent, or law;</li><li>a statement that the information in your notice is accurate and that you are the rights owner or authorized to act on behalf of the rights owner; and</li><li>your physical or electronic signature.</li></ul>
<p>We may remove, restrict, or disable access to content where appropriate and may request additional information before acting on a complaint.</p>
<h2>23. Third-Party Websites, Providers, and Services</h2>
<p>The Services may contain links to or integrations with government websites, payment processors, banks, financial service providers, registered agent providers, business address providers, mailing providers, identity-verification providers, software platforms, marketplaces, professional advisers, or other third parties.</p>
<p>Third parties operate independently and may have their own terms, fees, requirements, privacy policies, processing times, eligibility rules, and decisions. Steady Formation does not control and is not responsible for their services, availability, content, policies, requirements, decisions, acts, or omissions except to the extent required by applicable law.</p>
<p>Your use of a third-party service may require you to accept that third party&#x27;s terms or provide additional information directly to that third party.</p>
<h2>24. Service Availability, Changes, and Force Majeure</h2>
<p>We may add, modify, suspend, limit, or discontinue features, packages, prices, service areas, providers, dashboard access, or Services at any time, subject to any specific commitments we have already made for a paid order.</p>
<p>We may restrict access temporarily for maintenance, security, legal compliance, fraud prevention, provider requirements, or operational reasons.</p>
<p>We are not liable for delay or failure caused by events beyond our reasonable control, including government outages, third-party failures, provider delays, internet disruption, labor disputes, natural disasters, war, terrorism, civil unrest, public health events, cyber incidents, changes in law, payment network disruption, bank action, agency backlog, or other force majeure events.</p>
<h2>25. Disclaimer of Warranties</h2>
<p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICES ARE PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS.</p>
<p>STEADY FORMATION DISCLAIMS ALL WARRANTIES, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, ACCURACY, AVAILABILITY, AND COURSE OF DEALING.</p>
<p>WE DO NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, TIMELY, COMPLETE, OR SUITABLE FOR EVERY USER, BUSINESS, INDUSTRY, JURISDICTION, OR PURPOSE, OR THAT ANY GOVERNMENT OR THIRD-PARTY APPLICATION WILL BE APPROVED.</p>
<p>Nothing in these Terms excludes warranties, remedies, or rights that cannot lawfully be excluded.</p>
<h2>26. Limitation of Liability</h2>
<p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, STEADY FORMATION AND ITS AFFILIATES, OWNERS, OFFICERS, DIRECTORS, EMPLOYEES, CONTRACTORS, AGENTS, VENDORS, AND SERVICE PROVIDERS WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE, OR CONSEQUENTIAL DAMAGES, OR FOR LOST PROFITS, LOST REVENUE, LOST DATA, LOST GOODWILL, LOST BUSINESS OPPORTUNITIES, BUSINESS INTERRUPTION, SUBSTITUTE SERVICES, OR REPUTATIONAL HARM ARISING OUT OF OR RELATED TO THE SERVICES.</p>
<p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR TOTAL LIABILITY ARISING OUT OF OR RELATING TO A PARTICULAR PURCHASE, ORDER, SERVICE, OR CLAIM WILL NOT EXCEED THE STEADY FORMATION SERVICE FEES YOU PAID FOR THE AFFECTED PURCHASE OR SERVICE DURING THE 12 MONTHS BEFORE THE EVENT GIVING RISE TO THE CLAIM.</p>
<p>The limitations above apply whether the claim is based in contract, tort, negligence, strict liability, statute, warranty, equity, or any other legal theory, even if a remedy fails of its essential purpose.</p>
<p>These limitations do not apply where prohibited by law or to liability that cannot lawfully be limited.</p>
<h2>27. Indemnification</h2>
<p>To the extent permitted by law, you agree to indemnify, defend, and hold harmless Steady Formation and its affiliates, owners, officers, directors, employees, contractors, agents, vendors, and service providers from and against third-party claims, liabilities, damages, losses, penalties, fines, costs, and reasonable attorneys&#x27; fees arising from or related to:</p>
<ul><li>your use or misuse of the Services;</li><li>your breach of these Terms or applicable service terms;</li><li>materially false, inaccurate, incomplete, unauthorized, or unlawful information you provide;</li><li>your violation of law, regulation, sanctions rules, provider requirements, or third-party rights;</li><li>your business activities, filings, ownership structure, products, services, customers, or transactions; or</li><li>your failure to obtain required approvals, licenses, tax advice, professional advice, or compliance support.</li></ul>
<p>This section does not require you to indemnify us for our own fraud, willful misconduct, or liability that cannot be shifted under applicable law.</p>
<h2>28. Suspension and Termination</h2>
<p>You may stop using the Services at any time, subject to any payment obligations, renewal terms, cancellation rules, provider rules, or pending order responsibilities that apply.</p>
<p>We may suspend, restrict, or terminate access to the Services or decline to complete an order if you breach these Terms, fail to pay amounts due, provide inaccurate or unauthorized information, fail to respond to required requests, create legal or security risk, misuse the Services, engage in suspected fraud, or where suspension is reasonably necessary to comply with law or third-party requirements.</p>
<p>Termination does not automatically entitle you to a refund. Refund eligibility is governed by the <a href="/refund-policy" class="text-[#7856FC] hover:underline">Refund Policy</a> and applicable order terms.</p>
<p>Provisions that by their nature should survive termination will survive, including payment obligations, intellectual property provisions, warranty disclaimers, limitations of liability, indemnification, dispute-related provisions, and any rights or obligations needed to complete, document, or wind down an order.</p>
<h2>29. Governing Law</h2>
<p>Except where mandatory consumer law requires otherwise, these Terms and any dispute arising out of or related to the Services are governed by the laws of the State of Wyoming and applicable United States federal law, without regard to conflict-of-law principles.</p>
<h2>30. Dispute Resolution, Venue, Class-Action Waiver, and Jury-Trial Waiver</h2>
<p>Before filing a formal claim, you and Steady Formation agree to try to resolve the dispute informally by providing written notice that describes the dispute, the requested relief, and relevant account or order details. Notice to Steady Formation must be sent to <a href="mailto:info@steadyformation.com" class="text-[#7856FC] hover:underline">info@steadyformation.com</a> or the mailing address listed in Section 35.</p>
<p>If the dispute is not resolved informally within 30 days after notice is received, either party may bring the dispute in a court of competent jurisdiction serving Sheridan County, Wyoming, unless applicable law gives you the right to bring a claim elsewhere.</p>
<p>To the maximum extent permitted by law, you and Steady Formation agree that any dispute will be brought only on an individual basis and not as a plaintiff, class member, or representative in any class, collective, consolidated, private attorney general, or representative proceeding.</p>
<p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, YOU AND STEADY FORMATION KNOWINGLY AND VOLUNTARILY WAIVE ANY RIGHT TO A TRIAL BY JURY IN ANY ACTION, CLAIM, OR PROCEEDING ARISING OUT OF OR RELATED TO THESE TERMS OR THE SERVICES.</p>
<p>Nothing in this section prevents either party from seeking temporary or preliminary injunctive relief where necessary to protect intellectual property, confidential information, security, systems, users, or legal rights.</p>
<h2>31. Changes to These Terms</h2>
<p>We may update these Terms from time to time. The updated version will be posted on our website with a revised &quot;Last Updated&quot; date.</p>
<p>Where required by law or where a change is materially adverse, we may provide additional notice. Your continued use of the Services after updated Terms become effective constitutes acceptance of the revised Terms to the extent permitted by law.</p>
<p>The version in effect at the time of purchase will generally govern that purchase, unless a later version is more favorable to you, the parties agree otherwise, or applicable law requires otherwise.</p>
<h2>32. Assignment</h2>
<p>You may not assign or transfer these Terms, your account, or your rights or obligations under these Terms without our prior written consent.</p>
<p>We may assign or transfer these Terms in connection with a merger, acquisition, reorganization, financing, sale of assets, change of control, affiliate restructuring, or transfer of the Services, provided that the assignment is consistent with applicable law.</p>
<h2>33. Severability and No Waiver</h2>
<p>If any provision of these Terms is held invalid, unlawful, or unenforceable, it will be limited or removed only to the minimum extent necessary, and the remaining provisions will remain in effect.</p>
<p>Our failure to enforce a provision is not a waiver of our right to enforce it later. A waiver is effective only if it is in writing and signed by an authorized representative of Steady Formation.</p>
<h2>34. Entire Agreement</h2>
<p>These Terms, together with our <a href="/privacy" class="text-[#7856FC] hover:underline">Privacy Policy</a>, <a href="/refund-policy" class="text-[#7856FC] hover:underline">Refund Policy</a>, applicable order details, checkout disclosures, service-specific terms, and any additional written terms expressly incorporated into your purchase, constitute the agreement between you and Steady Formation regarding the Services.</p>
<p>If there is a conflict between these Terms and a service-specific written disclosure for a particular order, the service-specific disclosure controls for that order only to the extent of the conflict.</p>
<h2>35. Contact Us</h2>
<p>For questions about these Terms or the Services, contact:</p>
<address class="policy-address">Steady Formation<br />75 E 3RD ST STE A70<br />Sheridan, WY 82801<br />United States<br />Email: <a href="mailto:info@steadyformation.com" class="text-[#7856FC] hover:underline">info@steadyformation.com</a><br />Phone: <a href="tel:+13074001666" class="text-[#7856FC] hover:underline">+1 (307) 400-1666</a><br />Website: <a href="https://steadyformation.com/" target="_blank" rel="noopener noreferrer" class="text-[#7856FC] hover:underline">https://steadyformation.com/</a></address>`;

export default function TermsOfServicePage() {
  return (
    <div>
      <PageHeader
        title="Terms of Service"
        subTitle="The terms that govern your access to and use of the Steady Formation website, dashboard, and related services."
        page="Terms of Service"
      />
      <div className="w-full bg-white">
        <div className="w-full max-w-[980px] lg:max-w-[800px] mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-16">
          <div
            className="policy-content blog-content font-inter text-[16px] leading-[24px] md:text-[18px] md:leading-[28px] font-normal text-[#475467]"
            dangerouslySetInnerHTML={{ __html: termsOfServiceHtml }}
          />
        </div>
      </div>
    </div>
  );
}
